Repository TheLastPush/Intro, pull requests merged in 2025-05, with the labels that each got.

#9 [Feat] 메인 화면 및 멤버 카드 구현
  theLastPush/theLastPush/Common/Model/MemberData.swift
  theLastPush/theLastPush/Resources/Assets.xcassets/IntroButton.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/IntroButton.imageset/IntroButton.png
  theLastPush/theLastPush/Resources/Assets.xcassets/member1.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/member1.imageset/member1.png
  theLastPush/theLastPush/Resources/Assets.xcassets/member2.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/member2.imageset/member2.png
  theLastPush/theLastPush/Resources/Assets.xcassets/member3.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/member3.imageset/member3.png
  theLastPush/theLastPush/Resources/Assets.xcassets/member4.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/member4.imageset/member4.png
  theLastPush/theLastPush/Resources/Info.plist
  theLastPush/theLastPush/Screens/Main/MainVC.swift
  theLastPush/theLastPush/Screens/Main/MemberCell.swift
Labels: 🪢 Chore, 🎨 UI

#14 [Feat] 조성준 개인 페이지 구현 #11
  theLastPush/theLastPush/Common/Extensions/UIFont+.swift
  theLastPush/theLastPush/Resources/Assets.xcassets/github.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/github.imageset/github.png
  theLastPush/theLastPush/Resources/Assets.xcassets/juseojoNotion.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/juseojoNotion.imageset/my-notion-face-portrait.png
  theLastPush/theLastPush/Resources/Assets.xcassets/juseojoProfile.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/juseojoProfile.imageset/beauty_1679078666344.png
  theLastPush/theLastPush/Resources/Assets.xcassets/velog.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/velog.imageset/velog.jpeg
  theLastPush/theLastPush/Resources/Info.plist
  theLastPush/theLastPush/Screens/JuseojoVC/JuseojoVC.swift
  theLastPush/theLastPush/Screens/JuseojoVC/JuseojoView.swift
Labels: 🎨 UI

#18 [Feat] VC 전환을 위한 네비게이션, present 구성 및 폰트 익스텐션 추가 #17
  theLastPush/theLastPush/Application/SceneDelegate.swift
  theLastPush/theLastPush/Common/Extensions/UIFont+.swift
  theLastPush/theLastPush/Screens/JuseojoVC/JuseojoVC.swift
  theLastPush/theLastPush/Screens/JuseojoVC/JuseojoView.swift
  theLastPush/theLastPush/Screens/Main/MainVC.swift
  theLastPush/theLastPush/Screens/Onboarding/OnboardingVC.swift
  theLastPush/theLastPush/Screens/Onboarding/OnboardingView.swift
Labels: 🪢 Chore

#21 [Feat] 개인 페이지 구현
  theLastPush/theLastPush/Common/Extensions/UIColor+.swift
  theLastPush/theLastPush/Common/Model/MemberData.swift
  theLastPush/theLastPush/Resources/Assets.xcassets/tistory.imageset/Contents.json
  theLastPush/theLastPush/Resources/Assets.xcassets/tistory.imageset/tistory.png
  theLastPush/theLastPush/Screens/Main/MainVC.swift
  theLastPush/theLastPush/Screens/MilouVC/AnswerCell.swift
  theLastPush/theLastPush/Screens/MilouVC/MilouVC.swift
  theLastPush/theLastPush/Screens/MilouVC/QuestionCell.swift
Labels: 🪢 Chore, 🎨 UI

#24 [Feat] 서광용 개인 페이지 구현
  theLastPush/theLastPush/Screens/MoriVC/MoriVC.swift
Labels: 🪢 Chore, 🎨 UI

#32 [Feat] 메인페이지 리팩토링
  theLastPush/theLastPush/Screens/Main/MainVC.swift
  theLastPush/theLastPush/Screens/Main/MainView.swift
  theLastPush/theLastPush/Screens/Main/MemberCell.swift
  theLastPush/theLastPush/Screens/Main/MemberCollectionView.swift
Labels: 🪢 Chore, 💻 Logic

#38 [Chore] 폴더링 수정
  theLastPush/theLastPush/Screens/Juseojo/JuseojoVC.swift
  theLastPush/theLastPush/Screens/Juseojo/JuseojoView.swift
  theLastPush/theLastPush/Screens/Main/MainView.swift
  theLastPush/theLastPush/Screens/Main/MemberCollectionView.swift
  theLastPush/theLastPush/Screens/Milou/Cell/AnswerCell.swift
  theLastPush/theLastPush/Screens/Milou/Cell/QuestionCell.swift
  theLastPush/theLastPush/Screens/Milou/ChattingTableView.swift
  theLastPush/theLastPush/Screens/Milou/Message.swift
  theLastPush/theLastPush/Screens/Milou/MilouVC.swift
  theLastPush/theLastPush/Screens/Milou/MilouView.swift
  theLastPush/theLastPush/Screens/Mori/MoriVC.swift
  theLastPush/theLastPush/Screens/Pudding/PuddingVC.swift
Labels: 🪢 Chore
